# Generated by Django 4.2.4 on 2023-08-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='CustomUser')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRestaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurants', to='favorites.favorite', verbose_name='Favorite')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.restaurants', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Favorite Restaurant',
                'verbose_name_plural': 'Favorite Restaurants',
            },
        ),
        migrations.CreateModel(
            name='FavoritePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_places', to='favorites.favorite', verbose_name='Favorite')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Favorite Place',
                'verbose_name_plural': 'Favorite Places',
            },
        ),
        migrations.CreateModel(
            name='FavoriteHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hotels', to='favorites.favorite', verbose_name='Favorite')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.hotels', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Favorite Hotel',
                'verbose_name_plural': 'Favorite Hotels',
            },
        ),
        migrations.CreateModel(
            name='FavoriteAttractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.attractions', verbose_name='Attraction')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_attractions', to='favorites.favorite', verbose_name='Favorite')),
            ],
            options={
                'verbose_name': 'Favorite Attraction',
                'verbose_name_plural': 'Favorite Attractions',
            },
        ),
    ]
