# Generated by Django 4.2.4 on 2023-08-24 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('contacts', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contacts')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
            },
        ),
        migrations.CreateModel(
            name='EventsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Events Category',
                'verbose_name_plural': 'Events Categories',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('car_parking', models.PositiveIntegerField(verbose_name='Car Parking')),
                ('pets', models.PositiveIntegerField(verbose_name='Pets')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('kitchen', models.BooleanField(default=False, verbose_name='Kitchen')),
                ('conditioner', models.BooleanField(default=False, verbose_name='Conditioner')),
                ('washer', models.BooleanField(default=False, verbose_name='Washer')),
                ('tv_netflix', models.BooleanField(default=False, verbose_name='TV with Netflix')),
                ('wifi', models.BooleanField(default=False, verbose_name='Free Wi-Fi')),
                ('balcony', models.BooleanField(default=False, verbose_name='Balcony or Patio')),
                ('garden', models.BooleanField(default=False, verbose_name='Green space or gardens')),
                ('car_rent', models.BooleanField(default=False, verbose_name='Car rental services')),
                ('hairdryer', models.BooleanField(default=False, verbose_name='Hairdryers')),
                ('iron_board', models.BooleanField(default=False, verbose_name='Iron and ironing board')),
                ('pool', models.BooleanField(default=False, verbose_name='Swimming pool')),
                ('gym', models.BooleanField(default=False, verbose_name='Fitness center or gym')),
                ('game_room', models.BooleanField(default=False, verbose_name='Game room')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='regions <django.db.models.fields.CharField>', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_range', models.CharField(max_length=100, verbose_name='Price Range')),
                ('specialized_menu', models.CharField(max_length=100, verbose_name='Specialized menu')),
                ('meal_time', models.CharField(max_length=100, verbose_name='Meal Time')),
                ('website', models.URLField(verbose_name='Website')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='places.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='WhatToTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_to_try', to='places.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'What to try',
                'verbose_name_plural': 'What to try',
            },
        ),
        migrations.CreateModel(
            name='WhatToTryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='what_to_try None', verbose_name='Image')),
                ('what_to_try', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.whattotry', verbose_name='What to try')),
            ],
            options={
                'verbose_name': 'What to try image',
                'verbose_name_plural': 'What to try images',
            },
        ),
        migrations.CreateModel(
            name='RestaurantsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants None', verbose_name='Image')),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.restaurants', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant image',
                'verbose_name_plural': 'Restaurant images',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='place None', verbose_name='Image')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Place image',
                'verbose_name_plural': 'Place images',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='HotelsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels None', verbose_name='Image')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.hotels', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel image',
                'verbose_name_plural': 'Hotel images',
            },
        ),
        migrations.AddField(
            model_name='hotels',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='places.place', verbose_name='Place'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.CharField(max_length=20, verbose_name='Time')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events <django.db.models.fields.CharField>', verbose_name='Poster')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='places.eventscategory', verbose_name='Events Category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='places.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='AttractionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions None', verbose_name='Image')),
                ('attractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.attractions', verbose_name='Attraction')),
            ],
            options={
                'verbose_name': 'Attraction image',
                'verbose_name_plural': 'Attraction images',
            },
        ),
        migrations.AddField(
            model_name='attractions',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='places.place', verbose_name='Place'),
        ),
    ]
