# Generated by Django 4.2.4 on 2023-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating'),
        ),
    ]
