# Generated by Django 4.2.4 on 2023-08-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_restaurantrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantrating',
            name='atmosphere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Atmosphere'),
        ),
        migrations.AddField(
            model_name='restaurantrating',
            name='nutrition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Nutrition'),
        ),
        migrations.AddField(
            model_name='restaurantrating',
            name='price_quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Price Quality'),
        ),
        migrations.AddField(
            model_name='restaurantrating',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Service'),
        ),
    ]
