# Generated by Django 4.2.4 on 2023-08-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_restaurantrating_atmosphere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantrating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Rating'),
        ),
    ]
