# Generated by Django 4.2.4 on 2023-08-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='culture_category/<django.db.models.fields.CharField>', verbose_name='image'),
        ),
    ]
