# Generated by Django 4.2.4 on 2023-08-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_culture_description_ar_culture_description_ch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='description_ch',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='name_ch',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='culturecategory',
            old_name='description_ch',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='culturecategory',
            old_name='name_ch',
            new_name='name_zh_hans',
        ),
    ]
